# Generated by Django 3.0.4 on 2020-03-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='type',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Ingredients_Meals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('additional_info', models.CharField(blank=True, max_length=255)),
                ('ingredients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Ingredients')),
                ('meals_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Meals')),
            ],
        ),
    ]
