# Generated by Django 3.0.4 on 2020-03-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200305_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients_meals',
            old_name='ingredients_id',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='ingredients_meals',
            old_name='meals_id',
            new_name='meals',
        ),
    ]
