# Generated by Django 3.0.4 on 2020-04-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20200408_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients_meals',
            name='measure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='measure',
        ),
    ]
